brace_style = "PreferSameLine"
color = "Always"
report_fixme = "Always"
report_todo = "Always"
space_after_colon = true
space_before_colon = false
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_try_shorthand = true
tab_spaces = 4
merge_imports = true
merge_derives = true
newline_style = "Unix"
